;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_screensize
	.import		_screen
	.export		_screen_init

; ---------------------------------------------------------------
; unsigned char __near__ screen_init (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_screen_init: near

.segment	"BSS"

L0003:
	.res	1,$00
L0005:
	.res	1,$00

.segment	"CODE"

	lda     #$00
	sta     L0003
	sta     L0005
	lda     #<(L0003)
	ldx     #>(L0003)
	jsr     pushax
	lda     #<(L0005)
	ldx     #>(L0005)
	jsr     _screensize
	lda     L0003
	sta     _screen
	lda     L0005
	sta     _screen+1
	ldx     #$00
	lda     _screen
	cmp     #$28
	beq     L0035
	lda     #$01
	rts
L0035:	txa
	sta     _screen+2
	sta     _screen+2+1
	lda     _screen
	jsr     decax1
	sta     _screen+4
	stx     _screen+4+1
	ldx     #$00
	lda     _screen+1
	jsr     decax1
	jsr     pushax
	lda     _screen
	jsr     tosumula0
	sta     _screen+6
	stx     _screen+6+1
	lda     _screen+1
	jsr     pusha0
	lda     _screen
	jsr     tosumula0
	jsr     decax1
	sta     _screen+8
	stx     _screen+8+1
	ldx     #$00
	lda     _screen+1
	jsr     decax6
	jsr     pushax
	lda     _screen
	jsr     tosumula0
	sta     _screen+10
	stx     _screen+10+1
	ldx     #$00
	lda     _screen
	jsr     decax8
	sta     _screen+12
	stx     _screen+12+1
	lda     #$01
	sta     _screen+16
	lda     _screen+1
	sec
	sbc     #$05
	sta     _screen+17
	lda     _screen
	jsr     pusha0
	lda     _screen+1
	jsr     tosumula0
	sta     _screen+14
	stx     _screen+14+1
	cpx     #$00
	bne     L002B
	cmp     #$00
	bne     L002B
	lda     #$01
	rts
L002B:	lda     #$8E
	jsr     $ffd2
	ldx     #$00
	txa
	rts

.endproc

