;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_screen
	.export		_string_len

.segment	"BSS"

_screen:
	.res	18,$00

; ---------------------------------------------------------------
; unsigned short __near__ string_len (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_string_len: near

.segment	"BSS"

L0016:
	.res	2,$00

.segment	"CODE"

	jsr     pushax
	lda     #$00
	sta     L0016
	sta     L0016+1
L0017:	ldx     L0016+1
	cpx     #$02
	bcs     L0018
	jsr     ldax0sp
	clc
	adc     L0016
	sta     ptr1
	txa
	adc     L0016+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$FF
	bne     L001F
	lda     L0016
	ldx     L0016+1
	jmp     incsp2
L001F:	jsr     ldax0sp
	clc
	adc     L0016
	sta     ptr1
	txa
	adc     L0016+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$24
	bne     L0019
	lda     L0016
	ldx     L0016+1
	jmp     incsp2
L0019:	lda     L0016
	ldx     L0016+1
	jsr     incax1
	sta     L0016
	stx     L0016+1
	jmp     L0017
L0018:	ldx     #$00
	txa
	jmp     incsp2

.endproc

