;
; File generated by cc65 v 2.18 - Ubuntu 2.18-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.18-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_cbm_k_chkin
	.import		_cbm_k_close
	.import		_cbm_k_getin
	.import		_cbm_k_open
	.import		_cbm_k_readst
	.import		_cbm_k_setlfs
	.import		_cbm_k_setnam
	.import		_cputsxy
	.import		_atoi
	.import		_screen
	.export		_open_file
	.export		_close_file
	.export		_read_weapon
	.export		_current_device
	.export		_current_sub_device

.segment	"RODATA"

L006F:
	.byte	$45,$52,$52,$4F,$52,$3A,$20,$44,$41,$54,$41,$46,$49,$4C,$45,$20
	.byte	$49,$54,$45,$4D,$20,$4E,$4F,$54,$20,$46,$4F,$55,$4E,$44,$00
L0061:
	.byte	$45,$52,$52,$4F,$52,$3A,$20,$52,$45,$41,$44,$49,$4E,$47,$20,$44
	.byte	$41,$54,$41,$46,$49,$4C,$45,$00
L0024:
	.byte	$45,$52,$52,$4F,$52,$3A,$20,$44,$45,$56,$49,$43,$45,$20,$4E,$4F
	.byte	$54,$20,$46,$4F,$55,$4E,$44,$00
L0037:
	.byte	$45,$52,$52,$4F,$52,$3A,$20,$46,$49,$4C,$45,$20,$4E,$4F,$54,$20
	.byte	$46,$4F,$55,$4E,$44,$00
L0075:
	.byte	$4F,$4B,$3A,$20,$44,$41,$54,$41,$46,$49,$4C,$45,$20,$52,$45,$41
	.byte	$44,$00
L0041:
	.byte	$45,$52,$52,$4F,$52,$3A,$20,$46,$49,$4C,$45,$48,$41,$4E,$44,$4C
	.byte	$45,$00
L002E:
	.byte	$45,$52,$52,$4F,$52,$3A,$20,$46,$49,$4C,$45,$4E,$41,$4D,$45,$00

; ---------------------------------------------------------------
; unsigned char __near__ open_file (unsigned char, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_open_file: near

.segment	"BSS"

L0017:
	.res	1,$00
L0019:
	.res	1,$00

.segment	"CODE"

	jsr     pushax
	lda     #$00
	sta     L0017
	sta     L0019
	ldy     #$02
	lda     (sp),y
	jsr     pusha
	lda     #$08
	jsr     pusha
	lda     #$00
	jsr     _cbm_k_setlfs
	jsr     _cbm_k_readst
	tax
	beq     L001F
	lda     _screen+16
	jsr     pusha
	lda     _screen+17
	jsr     pusha
	lda     #<(L0024)
	ldx     #>(L0024)
	jsr     _cputsxy
	ldx     #$00
	lda     #$02
	jmp     incsp3
L001F:	jsr     ldax0sp
	jsr     _cbm_k_setnam
	jsr     _cbm_k_readst
	tax
	beq     L0029
	lda     _screen+16
	jsr     pusha
	lda     _screen+17
	jsr     pusha
	lda     #<(L002E)
	ldx     #>(L002E)
	jsr     _cputsxy
	ldx     #$00
	lda     #$02
	jmp     incsp3
L0029:	jsr     _cbm_k_open
	jsr     _cbm_k_readst
	tax
	beq     L0032
	lda     _screen+16
	jsr     pusha
	lda     _screen+17
	jsr     pusha
	lda     #<(L0037)
	ldx     #>(L0037)
	jsr     _cputsxy
	ldx     #$00
	lda     #$02
	jmp     incsp3
L0032:	ldy     #$02
	lda     (sp),y
	jsr     _cbm_k_chkin
	jsr     _cbm_k_readst
	tax
	beq     L0016
	lda     _screen+16
	jsr     pusha
	lda     _screen+17
	jsr     pusha
	lda     #<(L0041)
	ldx     #>(L0041)
	jsr     _cputsxy
	ldx     #$00
	lda     #$02
	jmp     incsp3
L0016:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ close_file (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_close_file: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	lda     (sp),y
	jsr     _cbm_k_close
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ read_weapon (__near__ struct $anon-struct-0009 *, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_read_weapon: near

.segment	"BSS"

L004A:
	.res	50,$00
L004B:
	.res	1,$00
L004C:
	.res	1,$00

.segment	"CODE"

	jsr     pusha
	lda     #$00
	sta     L004C
	sta     L004B
	tax
L0084:	lda     L004B
	cmp     #$03
	bcs     L0085
	lda     #<(L004A)
	ldx     #>(L004A)
	clc
	adc     L004B
	bcc     L0058
	inx
L0058:	jsr     pushax
	jsr     _cbm_k_getin
	ldy     #$00
	jsr     staspidx
	jsr     _cbm_k_readst
	sta     L004C
	lda     L004C
	beq     L0050
	lda     _screen+16
	jsr     pusha
	lda     _screen+17
	jsr     pusha
	lda     #<(L0061)
	ldx     #>(L0061)
	jsr     _cputsxy
	ldx     #$00
	lda     #$02
	jmp     incsp3
L0050:	tax
	inc     L004B
	jmp     L0084
L0085:	lda     L004B
	jsr     incax1
	clc
	adc     #<(L004A)
	sta     ptr1
	txa
	adc     #>(L004A)
	sta     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	ldy     #$04
	jsr     pushwysp
	lda     #<(L004A)
	ldx     #>(L004A)
	jsr     _atoi
	ldy     #$00
	jsr     staspidx
	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     (sp),y
	beq     L006A
	lda     _screen+16
	jsr     pusha
	lda     _screen+17
	jsr     pusha
	lda     #<(L006F)
	ldx     #>(L006F)
	jsr     _cputsxy
	ldx     #$00
	lda     #$02
	jmp     incsp3
L006A:	lda     _screen+16
	jsr     pusha
	lda     _screen+17
	jsr     pusha
	lda     #<(L0075)
	ldx     #>(L0075)
	jsr     _cputsxy
	ldx     #$00
	txa
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ current_device (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_current_device: near

.segment	"CODE"

	ldx     #$00
	lda     $00D4
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ current_sub_device (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_current_sub_device: near

.segment	"CODE"

	ldx     #$00
	lda     $00D3
	rts

.endproc

