// This is an autogenerated header file featuring
// all of the weapon classes, types, etc which are
// defined in datafiles/weapons.py - DO NOT EDIT!

// Weapon types
#define WEAPON_TYPE_1H 1
#define WEAPON_TYPE_2H 2

// Weapon classes
#define WEAPON_CLASS_SIMPLE 1
#define WEAPON_CLASS_MARTIAL 2
#define WEAPON_CLASS_EXOTIC 3
#define WEAPON_CLASS_RANGED 4
#define WEAPON_CLASS_MAGICAL 5

// Weapon rarity
#define WEAPON_RARITY_COMMON 1
#define WEAPON_RARITY_UNCOMMON 2
#define WEAPON_RARITY_RARE 3
#define WEAPON_RARITY_LEGENDARY 4
