#include "msxgl.h"
#include "bios_var.h"

const u8 __at(M_RDPRIM) g_RDPRIM[5];
const u8 __at(M_WRPRIM) g_WRPRIM[7];
const u8 __at(M_CLPRIM) g_CLPRIM[14];
const u16 __at(M_USRTAB) g_USRTAB[10];
u8 __at(M_LINL40) g_LINL40;
u8 __at(M_LINL32) g_LINL32;
u8 __at(M_LINLEN) g_LINLEN;
u8 __at(M_CRTCNT) g_CRTCNT;
u8 __at(M_CLMLST) g_CLMLST;
u16 __at(M_TXTNAM) g_TXTNAM;
u16 __at(M_TXTCOL) g_TXTCOL;
u16 __at(M_TXTCGP) g_TXTCGP;
u16 __at(M_TXTATR) g_TXTATR;
u16 __at(M_TXTPAT) g_TXTPAT;
u16 __at(M_T32NAM) g_T32NAM;
u16 __at(M_T32COL) g_T32COL;
u16 __at(M_T32CGP) g_T32CGP;
u16 __at(M_T32ATR) g_T32ATR;
u16 __at(M_T32PAT) g_T32PAT;
u16 __at(M_GRPNAM) g_GRPNAM;
u16 __at(M_GRPCOL) g_GRPCOL;
u16 __at(M_GRPCGP) g_GRPCGP;
u16 __at(M_GRPATR) g_GRPATR;
u16 __at(M_GRPPAT) g_GRPPAT;
u16 __at(M_MLTNAM) g_MLTNAM;
u16 __at(M_MLTCOL) g_MLTCOL;
u16 __at(M_MLTCGP) g_MLTCGP;
u16 __at(M_MLTATR) g_MLTATR;
u16 __at(M_MLTPAT) g_MLTPAT;
u8 __at(M_CLIKSW) g_CLIKSW;
u8 __at(M_CSRY) g_CSRY;
u8 __at(M_CSRX) g_CSRX;
const u8 __at(M_CNSDFG) g_CNSDFG;
const u8 __at(M_RG0SAV) g_RG0SAV;
const u8 __at(M_RG1SAV) g_RG1SAV;
const u8 __at(M_RG2SAV) g_RG2SAV;
const u8 __at(M_RG3SAV) g_RG3SAV;
const u8 __at(M_RG4SAV) g_RG4SAV;
const u8 __at(M_RG5SAV) g_RG5SAV;
const u8 __at(M_RG6SAV) g_RG6SAV;
const u8 __at(M_RG7SAV) g_RG7SAV;
const u8 __at(M_STATFL) g_STATFL;
const u8 __at(M_TRGFLG) g_TRGFLG;
u8 __at(M_FORCLR) g_FORCLR;
u8 __at(M_BAKCLR) g_BAKCLR;
u8 __at(M_BDRCLR) g_BDRCLR;
const u8 __at(M_MAXUPD) g_MAXUPD[3];
const u8 __at(M_MINUPD) g_MINUPD[3];
u8 __at(M_ATRBYT) g_ATRBYT;
const u16 __at(M_QUEUES) g_QUEUES;
const u8 __at(M_FRCNEW) g_FRCNEW;
const u8 __at(M_SCNCNT) g_SCNCNT;
const u8 __at(M_REPCNT) g_REPCNT;
const u16 __at(M_PUTPNT) g_PUTPNT;
const u16 __at(M_GETPNT) g_GETPNT;
const CassetteIO __at(M_CS120) g_CS120;
const CassetteIO __at(M_CS240) g_CS240;
const u8 __at(M_LOW) g_LOW[2];
const u8 __at(M_HIGH) g_HIGH[2];
const u8 __at(M_HEADER) g_HEADER;
const u16 __at(M_ASPCT1) g_ASPCT1;
const u16 __at(M_ASPCT2) g_ASPCT2;
c8 __at(M_FNKSTR) g_FNKSTR[10][16];
u16 __at(M_CLOC) g_CLOC;
u8 __at(M_CMASK) g_CMASK;
const RS232Queue __at(M_QUETAB) g_QUETAB[4];
const u8 __at(M_QUEBAK) g_QUEBAK;
const u8 __at(M_VOICAQ) g_VOICAQ[128];
const u8 __at(M_VOICBQ) g_VOICBQ[128];
const u8 __at(M_VOICCQ) g_VOICCQ[128];
const u8 __at(M_RS2IQ) g_RS2IQ[64];
const u8 __at(M_DPPAGE) g_DPPAGE;
const u8 __at(M_ACPAGE) g_ACPAGE;
const u8 __at(M_AVCSAV) g_AVCSAV;
const u8 __at(M_EXBRSA) g_EXBRSA;
const u8 __at(M_CHRCNT) g_CHRCNT;
const u16 __at(M_ROMA) g_ROMA;
const u8 __at(M_MODE) g_MODE;
const u8 __at(M_NORUSE) g_NORUSE;
const u8 __at(M_XSAVE) g_XSAVE[2];
const u8 __at(M_YSAVE) g_YSAVE[2];
u8 __at(M_LOGOPR) g_LOGOPR;
const u8 __at(M_RSTMP) g_RSTMP;
const u8 __at(M_TOCNT) g_TOCNT;
const u16 __at(M_RSFCB) g_RSFCB;
const u8 __at(M_RSIQLN) g_RSIQLN;
const RS232Hook __at(M_MEXBIh) g_MEXBIh;
const RS232Hook __at(M_OLDSTT) g_OLDSTT;
const RS232Hook __at(M_OLDINT) g_OLDINT;
const u8 __at(M_DEVNUM) g_DEVNUM;
const RS232Area __at(M_DATCNT) g_DATCNT;
const u8 __at(M_ERRORS) g_ERRORS;
const u8 __at(M_FLAGS) g_FLAGS;
const u8 __at(M_ESTBLS) g_ESTBLS;
const u8 __at(M_COMMSK) g_COMMSK;
const u8 __at(M_LSTCOM) g_LSTCOM;
const u8 __at(M_LSTMOD) g_LSTMOD;
const u8 __at(M_PRSCNT) g_PRSCNT;
const u16 __at(M_SAVSP) g_SAVSP;
const u8 __at(M_VOICEN) g_VOICEN;
const u16 __at(M_SAVVOL) g_SAVVOL;
const u8 __at(M_MCLLEN) g_MCLLEN;
const u16 __at(M_MCLPTR) g_MCLPTR;
const u8 __at(M_QUEUEN) g_QUEUEN;
const u8 __at(M_MUSICF) g_MUSICF;
const u8 __at(M_PLYCNT) g_PLYCNT;
const u8 __at(M_VCBA) g_VCBA[37];
const u8 __at(M_VCBB) g_VCBB[37];
const u8 __at(M_VCBC) g_VCBC[37];
const u8 __at(M_ENSTOP) g_ENSTOP;
const u8 __at(M_BASROM) g_BASROM;
const u8 __at(M_LINTTB) g_LINTTB[24];
const u16 __at(M_FSTPOS) g_FSTPOS;
const u8 __at(M_CODSAV) g_CODSAV;
const u8 __at(M_FNKSWI) g_FNKSWI;
const u8 __at(M_FNKFLG) g_FNKFLG[10];
const u8 __at(M_ONGSBF) g_ONGSBF;
const u8 __at(M_CLIKFL) g_CLIKFL;
const u8 __at(M_OLDKEY) g_OLDKEY[11];
const u8 __at(M_NEWKEY) g_NEWKEY[11];
const u8 __at(M_KEYBUF) g_KEYBUF[40];
const u8 __at(M_LINWRK) g_LINWRK[40];
const u8 __at(M_PATWRK) g_PATWRK[8];
const u16 __at(M_BOTTOM) g_BOTTOM;
const u16 __at(M_HIMEM) g_HIMEM;
const u8 __at(M_TRPTBL) g_TRPTBL[78];
const u8 __at(M_RTYCNT) g_RTYCNT;
const u8 __at(M_INTFLG) g_INTFLG;
const u8 __at(M_PADY) g_PADY;
const u8 __at(M_PADX) g_PADX;
const u16 __at(M_JIFFY) g_JIFFY;
const u16 __at(M_INTVAL) g_INTVAL;
const u16 __at(M_INTCNT) g_INTCNT;
const u8 __at(M_LOWLIM) g_LOWLIM;
const u8 __at(M_WINWID) g_WINWID;
const u8 __at(M_GRPHED) g_GRPHED;
const u8 __at(M_ESCCNT) g_ESCCNT;
const u8 __at(M_INSFLG) g_INSFLG;
const u8 __at(M_CSRSW) g_CSRSW;
const u8 __at(M_CSTYLE) g_CSTYLE;
const u8 __at(M_CAPST) g_CAPST;
const u8 __at(M_KANAST) g_KANAST;
const u8 __at(M_KANAMD) g_KANAMD;
const u8 __at(M_FLBMEM) g_FLBMEM;
const u8 __at(M_SCRMOD) g_SCRMOD;
const u8 __at(M_OLDSCR) g_OLDSCR;
const u8 __at(M_CASPRV) g_CASPRV;
const u8 __at(M_BRDATR) g_BRDATR;
const u8 __at(M_GXPOS) g_GXPOS;
const u8 __at(M_GYPOS) g_GYPOS;
u8 __at(M_GRPACX) g_GRPACX;
u8 __at(M_GRPACY) g_GRPACY;
const u8 __at(M_DRWFLG) g_DRWFLG;
const u8 __at(M_DRWSCL) g_DRWSCL;
const u8 __at(M_DRWANG) g_DRWANG;
const u8 __at(M_MNROM) g_MNROM;
const u8 __at(M_EXPTBL) g_EXPTBL[4];
const u8 __at(M_SLTTBL) g_SLTTBL[4];
const u8 __at(M_SLTATR) g_SLTATR[64];
const u8 __at(M_SLTWRK) g_SLTWRK[128];
const u8 __at(M_PROCNM) g_PROCNM[16];
const u8 __at(M_RG08SAV) g_RG08SAV;
const u8 __at(M_RG09SAV) g_RG09SAV;
const u8 __at(M_RG10SAV) g_RG10SAV;
const u8 __at(M_RG11SAV) g_RG11SAV;
const u8 __at(M_RG12SAV) g_RG12SAV;
const u8 __at(M_RG13SAV) g_RG13SAV;
const u8 __at(M_RG14SAV) g_RG14SAV;
const u8 __at(M_RG15SAV) g_RG15SAV;
const u8 __at(M_RG16SAV) g_RG16SAV;
const u8 __at(M_RG17SAV) g_RG17SAV;
const u8 __at(M_RG18SAV) g_RG18SAV;
const u8 __at(M_RG19SAV) g_RG19SAV;
const u8 __at(M_RG20SAV) g_RG20SAV;
const u8 __at(M_RG21SAV) g_RG21SAV;
const u8 __at(M_RG22SAV) g_RG22SAV;
const u8 __at(M_RG23SAV) g_RG23SAV;
const u8 __at(M_MINROM) g_MINROM;
const u8 __at(M_SVFFF8) g_SVFFF8[2];
const u8 __at(M_RG25SAV) g_RG25SAV;
const u8 __at(M_RG26SAV) g_RG26SAV;
const u8 __at(M_RG27SAV) g_RG27SAV;
const u8 __at(M_SVFFFD) g_SVFFFD[2];
u8 __at(M_SLTSL) g_SLTSL;